name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@release-40
    with:
      maven-test-run: false
      jdk-matrix: '[ "17", "21", "24" ]'
      maven-matrix: '[ "3.9.10" ]' # IT does the mvn matrix
      maven-test: './mvnw clean verify -e -B -V -P run-its -f it'

